<?php
    $recoverUrl = $this->user->getRecoverPassUrl();
?>
<?php if($this->mailVersion == 'text'){

    echo "Hola" . " " . $this->user->full_name . ",";
    echo "\n\n";
    echo "para recuperar tu contraseña ve a este link:";
    echo $recoverUrl;
} elseif($this->mailVersion == 'html') {?>
    Hola <?php echo $this->user->full_name; ?>,
    </br>
    </br>
    para recuperar tu contraseña ve a este link:
    </br>
    <a href="<?php echo $recoverUrl; ?>"><?php echo $recoverUrl; ?></a>
<?php }?>
    
(<?= $this->mailVersion ?>)