<form action="" method="POST">
    <h1><?=$this->tr("Adicionar")?></h1>
    <p><?=$this->tr("Nombre")?></p>
    <input type="text" name="name" class="required">
    <input type="hidden" name="id" value="0">
    <input type="hidden" name="id_transaction_type" value="0">
    <p><?=$this->tr("Categoria")?></p>
    <select name="id_category_type">
        <?php foreach($this->categories as $category){ ?>
            <?php if($category->id == 9) {?>
                <option value="<?= $category->id ?>" selected=""><?= $category->name?></option>
            <?php } else {?>
                <option value="<?= $category->id ?>"><?= $category->name?></option>
            <?php } ?>
        <?php }?>
    </select>
    <p><?=$this->tr("Valor")?></p>
    <input type="text" name="value" class="required money">
    <p><?=$this->tr("Fecha")?></p>
    <input type="text" name="date" class="date" readonly="true">
    <?php if(!$this->account->is_independent){ ?>
        <p>
            <input id="is_frequent" type="checkbox" name="is_frequent"/>
            <span><label for="is_frequent"><?=$this->tr("recurrente")?></label></span>
        </p>
        <div id="remove-frequency-warning" style="display: none;">
            <?=$this->tr("Si cancelas la recurrencia de esta transaccion ya no se volvera a repetir en tus proximos presupuestos.")?>
        </div>
        <p><?=$this->tr("Frecuencia")?></p>
        <select name="frequency_days" disabled="true" class="select-disabled">
            <option value="1"><?= $this->tr("diario");?></option>
            <option value="7"><?= $this->tr("semanal");?></option>
            <option value="14"><?= $this->tr("quincenal");?></option>
            <option value="-1"><?= $this->tr("mensual");?></option>
            <option value="0"><?= $this->tr("otro");?></option>
        </select>
        <input type="text" name="precise_frequency_days" disabled="true" class="input-disabled">
        <p><?=$this->tr("Numero de repeticiones")?></p>
        <select name="frequency_time" disabled="true" class="select-disabled">
            <option value="0"><?= $this->tr("indefinido");?></option>
            <?php for($i=1;$i<=30;$i++){ ?>
                <option value="<?= $i ?>"><?= $i?></option>
            <?php }?>
        </select>
    <?php }?>
    <input type="submit" value="<?= $this->tr("Crear")?>" />
    <!--Remover div-->
    <div>
        <a href="#" class="less-options"> <?= $this->tr("Menos opciones...")?> </a>
    </div>
 </form>