<div id="login-container">
    <form id="login" action="" method="POST" class="text-align-center bg-color-transparent color-gray-1">

        <h3>Ingresa con tu cuenta de correo</h3>

        <h6>-</h6> <!--Separador-->

        <input 
            id="input-email" 
            type="text" 
            name="email" 
            class="required is_email input-text" 
            placeholder="Correo electrónico"
            /> 

        <h6>-</h6> <!--Separador-->

        <input 
            type="password" 
            name="password" 
            class="input-password required input-text" 
            placeholder="Contraseña"
            />

        <h6>-</h6> <!--Separador-->

        <input 
            type="submit" 
            value="Ingresar" 
            class="input-button"
            />  

    </form>
    <div class="response"></div>
</div>