<h1>Crear categoria</h1>

<div class="response"></div>
<form action="" method="POST" id="create-category">
    <div>
        <label>Nombre</label>
        <input type="" name="name" class="required" />
    </div>
    <div>
        <label>Detalles</label>
        <textarea name="details" cols="50" rows="5"></textarea>
    </div>
    <div>
        <input type="submit" value="Crear"/>
    </div>
</form>