<?php $login = array("action" => "login", "controller" => "session", "module" => "public") ?> 
<?php $register = array("action" => "register", "controller" => "session", "module" => "public") ?>

<div class="border-radius-0 color-grey-1 form-box padding-20px">

    <form action="<?= $this->url($login); ?>" method="POST" class="text-align-center bg-color-transparent color-grey-1">

        <h3>Ingresa con tu cuenta de correo</h3>

        <h6>-</h6> <!--Separador-->

        <input 
            id="input-email" 
            type="text" 
            name="email" 
            class="required is_email input-text" 
            placeholder="Correo electrónico"
            /> 

        <h6>-</h6> <!--Separador-->

        <input 
            type="password" 
            name="password" 
            class="input-password required input-text" 
            placeholder="Contraseña"
            />

        <h6>-</h6> <!--Separador-->

        <input 
            type="submit" 
            value="Ingresar" 
            class="input-button"
            />  

    </form>
<!--    <p class="color-grey-1"></p>-->
    <p class="text-align-center"><a id="js-fancy-recover-password" href="#"><?= $this->tr("¿Olvidaste la contraseña?") ?></a></p>
       <h6>-</h6> <!--Separador-->

       <div class="separation-line-1px-dark-grey"></div>

    <p id="info" class="padding-0 margin-left-right-auto width-100-percent color-grey-1">Si aún no te has registrado, puedes hacerlo&nbsp;<a href="#" class="js-fancy-register">aquí</a>.</p>
</div>