<a href="#"><?= $this->about ?></a>

<div id="main-container" class="width-90-percent margin-left-right-auto border-radius-10px">
    <img src="<?= LINKS_URL ?>/images/team/title.png" class="width-50-percent text-align-center margin-left-25-percent"/>
    <!--                <h1 class="text-variant-small-caps text-align-center ">¡El equipo Quantups!</h1> -->
    <p><img src="<?= LINKS_URL ?>/images/team/team.png" class="width-95-percent border-color-grey-2 border-style-solid border-width-1px  border-radius-10px"/></p>
    <p class="color-transparent">·</p>
    <div class="position-float-left text-align-center width-20-percent margin-left-10-percent bg-color-white-3 border-color-grey-3 border-style-solid border-width-1px border-radius-10px">
        <img src="<?= LINKS_URL ?>/images/team/team-1.png" class="width-90-percent margin-top-15px"/>
        <div>
            <p></p>
            <div class="font-bold font-size-130-percent">
                Andres Peña Carmona
            </div> 
            <p>
                Consectetur adipiscing elit. Aenean porttitor mollis tellus, a pharetra elit imperdiet non.
            </p>
            <p><a href="#" target="_blank">Portafolio</a></p>
            <p></p>
        </div>
    </div> <!--Andrews-->
    <div class="position-float-left text-align-center width-20-percent margin-left-10-percent bg-color-white-3 border-color-grey-3 border-style-solid border-width-1px border-radius-10px">
        <img src="<?= LINKS_URL ?>/images/team/team-2.png" class="width-90-percent margin-top-15px"/>
        <div>
            <p></p>
            <div class="font-bold font-size-130-percent">
                Helman Rodríguez
            </div> 
            <p>
                Consectetur adipiscing elit. Aenean porttitor mollis tellus, a pharetra elit imperdiet non.
            </p>
            <p><a href="#" target="_blank">Portafolio</a></p>
            <p></p>
        </div>
    </div> <!--Hel-->

    <div class="position-float-left text-align-center width-20-percent margin-left-10-percent bg-color-white-3 border-color-grey-3 border-style-solid border-width-1px border-radius-10px">
        <img src="<?= LINKS_URL ?>/images/team/team-3.png" class="width-90-percent margin-top-15px"/>
        <div>
            <p></p>
            <div class="font-bold font-size-130-percent">
                Exnius
            </div> 
            <p>
                Consectetur adipiscing elit. Aenean porttitor mollis tellus, a pharetra elit imperdiet non.
            </p>
            <p><a href="http://exnius.tk/" target="_blank">Portafolio</a></p>
            <p></p>
        </div>
    </div> <!--Exnius-->


    <div class="display-block position-float-clear-both"></div>
    <p class="color-transparent">·</p>
</div>