<div id="login-form" style="display: none;">
    <?php echo $this->render('partials/loginForm.phtml'); ?>
    <div class="response"></div>
</div>

<div id="register-form" style="display: none;">
    <?php echo $this->render('partials/registerForm.phtml'); ?>
    <div class="response"></div>
</div>

<div id="recover-password-form" style="display: none;">
    <?php echo $this->render('partials/recoverPassForm.phtml'); ?>
    <div class="response"></div>
</div>